//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMVCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student1Table_1
    {
        public string stud { get; set; }
        public string name { get; set; }
        public string class1 { get; set; }
        public string phone { get; set; }
        public int id { get; set; }
        public string allemail { get; set; }
    }
}
